sudo: false
language: node_js
notifications:
  email: "devs@scrollback.io"
cache:
  directories:
    - node_modules
node_js:
  - 'stable'
  - '5'
before_script:
  - echo '{}' > config/server.json
  - echo '{}' > config/client.json
  - npm run flow -- check
  - npm run build
script:
  - npm test -- --concurrency 5
